# Generated by Django 2.1.2 on 2018-10-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerinstance',
            name='container',
        ),
        migrations.DeleteModel(
            name='ContainerInstance',
        ),
    ]
