# Generated by Django 2.1.2 on 2018-11-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='image',
        ),
    ]
