# Generated by Django 2.1.2 on 2018-11-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_app'),
        ('containers', '0002_remove_container_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='app',
        ),
        migrations.AddField(
            model_name='container',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='images.Image'),
        ),
    ]
