# Generated by Django 2.1.2 on 2018-10-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181026_2007'),
        ('containers', '0002_auto_20181026_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='projects.Project'),
        ),
    ]
