# Generated by Django 2.1.2 on 2018-10-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_container_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='container',
            name='instance_number',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
