# Generated by Django 2.1.2 on 2018-11-06 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        ('containers', '0003_auto_20181107_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='apps.App'),
        ),
    ]
