# Generated by Django 2.1.3 on 2019-01-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_auto_20190131_2040'),
        ('containers', '0004_container_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='networks',
            field=models.ManyToManyField(related_name='containers', to='networks.NetworkBridge'),
        ),
    ]
