# Generated by Django 2.1.2 on 2018-10-31 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_auto_20181027_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='image',
        ),
        migrations.RemoveField(
            model_name='container',
            name='version',
        ),
    ]
