# Generated by Django 2.1.3 on 2019-01-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_container_networks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='networks',
            field=models.ManyToManyField(blank=True, null=True, related_name='containers', to='networks.NetworkBridge'),
        ),
    ]
