# Generated by Django 2.1.3 on 2019-02-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_auto_20190131_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='containers', to='networks.NetworkBridge'),
        ),
    ]
