# Generated by Django 2.1.2 on 2018-10-26 23:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181026_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
