# Generated by Django 2.1.3 on 2019-02-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_networks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='networks',
            new_name='network',
        ),
    ]
