# Generated by Django 2.1.3 on 2019-02-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190205_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='networks.NetworkBridge'),
        ),
    ]
