# Generated by Django 2.1.2 on 2018-10-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
