# Generated by Django 2.1.2 on 2018-10-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_git_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file_path',
        ),
    ]
