# Generated by Django 2.1.2 on 2018-10-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cloned',
            field=models.BooleanField(default=False),
        ),
    ]
