services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: database_superpassword
      POSTGRES_USER: database_user
      POSTGRES_DB: database_name
      PGDATA: /var/lib/postgresql/data/pgdata