# Generated by Django 2.1.3 on 2019-01-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='container_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
