# Generated by Django 2.1.2 on 2018-11-06 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('tag', models.CharField(blank=True, default='latest', max_length=30, null=True)),
                ('image_id', models.CharField(blank=True, max_length=30, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('local_build', models.BooleanField(default=True)),
                ('built', models.BooleanField(default=False)),
                ('last_version', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
