# Generated by Django 2.1.2 on 2018-10-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='local_build',
            field=models.BooleanField(default=True),
        ),
    ]
