# Generated by Django 2.1.2 on 2018-11-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_local_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='built',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='last_version',
            field=models.BooleanField(default=True),
        ),
    ]
