# Generated by Django 2.1.3 on 2019-02-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='ConfigFile',
        ),
    ]
