# Generated by Django 2.1.3 on 2019-02-09 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_app_load_balancer'),
        ('files', '0003_auto_20190209_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfile',
            name='app',
            field=models.ForeignKey(default="bef58b34-c0d2-484a-bfbe-b52f00bdb51d", on_delete=django.db.models.deletion.CASCADE, related_name='config_files', to='apps.App'),
            preserve_default=False,
        ),
    ]
