# Generated by Django 2.1.3 on 2019-02-10 00:30

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_project'),
        ('files', '0004_configfile_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfile',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_files', to='services.Service'),
        ),
        migrations.AlterField(
            model_name='configfile',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_files', to='apps.App'),
        ),
        migrations.AlterField(
            model_name='configfile',
            name='file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=files.models.update_config_file),
        ),
    ]
