# Generated by Django 2.1.3 on 2019-01-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkbridge',
            name='network_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
