# Generated by Django 5.1.4 on 2025-01-10 14:37

import apps.models
import core.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('data', models.JSONField(blank=True, default=apps.models.default_data)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('load_balancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='services.service')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.SerializeMixin, models.Model),
        ),
    ]
