# Generated by Django 2.1.2 on 2018-11-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='last_version',
        ),
    ]
