# Generated by Django 2.1.3 on 2018-11-13 16:09

import apps.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20181107_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=apps.models.default_data),
        ),
    ]
