# Generated by Django 2.1.3 on 2019-02-04 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('apps', '0004_auto_20181113_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='projects.Project'),
        ),
    ]
