# Generated by Django 2.1.3 on 2019-02-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_project'),
        ('apps', '0005_app_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='load_balancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='services.Service'),
        ),
    ]
